safe:             false
port:             7998
baseurl:          /roastedhusband/  # Where GitHub serves the project up from
url:              http://localhost:7998

source:           src
destination:      _gh_pages
plugins:          src/_plugins

pygments:         true
permalink:        pretty

# ensures SCSS files are compiled
include:          [_*.scss]

# used in building icon pages
icon_meta:        src/icons.yml
icon_layout:      icon.html    # Relative to _layouts directory
icon_destination: icon         # Relative to destination

fontawesome:
  version:        1.0.0
  minor_version:  1.0
  doc_blob:       v1.0.0
  site_title:     Roasted Husband
  fa_fnt_prefix:  font-awesome
  rh_fnt_prefix:  roasted-husband
  url:            http://www.roastedhusband.com
  legacy_url:     http://www.roastedhusband.com
  blog_url:       http://blog.roastedhusband.com
  twitter:        roastedhusband
  tagline:        The icon font for visual translations of Chinese restaurant menus 
  css_prefix:     rh
  author:
    name:         Tingshan Cavelti
    email:        tingshancavelti@fontawesome.io
    twitter:      tingshancavelti
    github:       roastedhusband
  github:
    url:          https://github.com/roastedhusband/roastedhusband
    project:      roastedhusband
    org:          roastedhusband
  license:
    font:
      version:      SIL OFL 1.1
      url:          http://scripts.sil.org/OFL
    code:
      version:      MIT License
      url:          http://opensource.org/licenses/mit-license.html
    documentation:
      version:      CC BY 3.0
      url:          http://creativecommons.org/licenses/by/3.0/

bootstrap:
  version:        3.2.0
  url:            http://getbootstrap.com

jquery:
  version:        1.11.1
